# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = ""
body = """
{%- for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
  {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
  {% if commit.remote.pr_number %} in \
    [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }})\
  {%- endif %}
{%- endfor %}
{% endfor %}

{%- if version %}
  {%- if previous.version %}
**Full Changelog**: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }}
  {%- endif %}
{%- endif %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '\\(#([0-9]+)\\)', replace = "" },
]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^doc", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^style", group = "Styling" },
  { message = "^ci", group = "CI/CD" },
  { message = "^chore", group = "Miscellaneous" },
  { message = "^build", group = "Build" },
  { message = "^revert", group = "Reverted" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"
